### ISSUE TITLE
loop taking a long time

### ISSUE THREAD

**Issue by hixfield** [myDevicesIoT/Cayenne-MQTT-Arduino#6]
I notice that the cayenne.loop() takes a long time to execute, looking at the code I think I see
a hardcoded delay of 1000 ms?

What is the reason for this value? Is there anything that we could do more intelligently to minimise the time spend in this loop function?

![screen shot 2016-12-23 at 11 41 10](https://cloud.githubusercontent.com/assets/9302613/21452152/213abb78-c905-11e6-8721-7c7f03bd7a70.png)

**Comment by jburhenn** [comment]
That loop is where all the MQTT processing occurs in order to send and receive messages. So it needs to be called regularly. We used the 1 second timeout to help prevent too much data from being sent to the server. However if you need to send data faster you can lower that value if you want. If we find a lot of users require finer granularity for that we may look into lowering the default.

**Comment by hixfield** [comment]
I am not convinced that building in a delay in the loop function is the best way to go.
The reason is that in nearly all cases the loop function does also do other processing not related to any Cayenne stuff. By implementing a delay in the cayenne's loop function you are actually compromising these other tasks that are part of the loop function.

I would suggest:

returning from the cayenne's loop function as fast as possible (no artificial delay), if you want to avoid that messages are send to fast, I would build in a timeout system based on the millis() function that only actually sends stuff if the time since the last communication was e.g. > 1 second. This is a better approach as it does not needlessly block the loop function. We have to consider that we are working on a single thread system, we should not block unless we really need some processing or there is any other good reason (e.g. timing).

**Comment by jburhenn** [comment]
The problem with a timeout that only sends stuff since the last communication is that would mean we'd have to drop messages that were happening too quickly, potentially losing important data. There isn't enough memory to cache them for later sending.

That's a good point about potentially compromising other tasks though. If you experiment and find a good timeout you think works well feel free to submit a pull request. Otherwise we may do some testing on our end when we get some time, though it may not happen for a little while.

**Comment by jburhenn** [comment]
Yield duration now configurable as parameter: https://github.com/myDevicesIoT/Cayenne-MQTT-Arduino/commit/be658763e41c12e40c94f6434a4459862639e490
